### ISSUE TITLE
Few fixes

### ISSUE THREAD

**Issue by Shachindra** [NetSepio/SmartContract#15]
1. Line 40 - 49
2. total_dapps_reviewed() -> total sites reviewed?
3. Check if metadata exists - what's the output?

**Comment by huisq** [comment]
1. Those are constants necessary for the functions. Not so important what their content is because we are not using them anyway. 
2. Noted, will rename.
3. This is to check if a review content (aka distinct review metadata) is already on chain.

**Comment by huisq** [comment]
resolved earlier
